apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-openshift-operators-redhat.yaml
  - namespace-openshift-logging.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - lokistack.yaml
