apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-openshift-logging.yaml
  - namespace-openshift-operators-redhat.yaml
  - operatorgroup.yaml
  - subscription.yaml

  - minio/pvc.yaml
  - minio/deployment.yaml
  - minio/service.yaml
  - minio/bucket-job.yaml

  - loki/s3-secret.yaml
  - loki/lokistack.yaml
